# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["justinliew@gmail.com"]
cloned_from = "https://github.com/fastly/compute-starter-kit-rust-default"
description = "Backend data for the Journeyman Game"
language = "rust"
manifest_version = 3
name = "journeyman"
service_id = "okVVq7XWELxYSj3Lh2BzGu"

[local_server]

[scripts]
  build = "cargo build --profile release"
